### PR TITLE
Open Logic 3.0.2

### PR DESCRIPTION
**Pull request by obruendl**

### CODE REVIEW

**Comment by obruendl** [comment]
@olofk I just upgraded to open-logic 3.0.1, please merge.

**Comment by obruendl** [comment]
@olofk Any update?

Is there any way to get PRs reacted on more quickly?

**Comment by olofk** [comment]
I think it's better to have several versioned .core files instead of updating the existing ones, like we do with the other cores in this library. Look at e.g. how wb_intercon does it. The reason is that this allows users to stay on the old version if they need to, and decide for themselves when to upgrade. I think this is especially important when doing major version upgrades.

**Comment by obruendl** [comment]
Thank you for the input. I will implement this (upload files for all releases).

**Comment by obruendl** [comment]
@olofk 

Done. I will from now on create a version folder for every release.

I did not invest time in uploading all older versions because due to the path issues the old versions didn't work anyways. Because this was not reported until now, I assume nobody used older versions through fusesoc-cores and hence there is no need to invest time into retaining older versions.

**Comment by obruendl** [comment]
@olofk 

Retaining all versions of open-logic will somewhen lead to a rather spammed core-list. Is there any option to instruct fusesoc to only import certain versions of a core? So users could import only the version they want to use although the repo they import contains many versions.

**Comment by olofk** [comment]
I don't have any clear guidelines here, but I typically keep the older versions around for a while (without a clear definition of a while :) ), especially when there are incompatible changes to allow users to upgrade at their own pace.

I get your point about spamming the core list. Perhaps the easiest solution is to add some switch to only print the latest version of a core. With that, it shouldn't really matter how many older versions we keep around.

**Comment by olofk** [comment]
And Open Logic 3.0.2 is now in the tree. Thank you for your contributions.

**Comment by obruendl** [comment]
@olofk 

Regarding spamming the cores list, I thinke one of the following options would be great:
- Allow "fusesoc library add" to import only core-files in a subdirectory of a git repo
- Allow "fusesoc library add" to only import core-files matching a VLNV regex (e.g. "open-logic:\*:\*:3.0.2")
- Allow "fusesoc library add" to import not only a repo but a specific ref in the repo (a commit, a tag,, a branch, ...)

Actually I believe the latest option would be most optimal. It looks a bit strange to me that "fusesoc library add" requires me to enter a repo (I can't use a tag or the like) but it does then only look at the head of the main branch.

I currently do not see a way to offer users to access all versions of open-logic without immediately spamming their cores-list.

**Pull request merged**
