### PR TITLE
De0 Nano Multicore

### PR DESCRIPTION
**Pull request by stffrdhrn**
Hello, sorry I tried to do this kind of quick because of kids running around.  Please let me know if any issues.

Also, I fixed a minor issue in the timer core you posted.  For now I migrated the sdram controller core as version r2 since that works.  Ill talk to stefan about adding a version.

### CODE REVIEW

**Comment by stffrdhrn** [comment]
Hi @olofk, did you see this one?

**Comment by olofk** [comment]
Hi,

Sorry for the late response. I saw it, but forgot. Thanks for reminding. I'll get to it when my kids stop running around

**Comment by stffrdhrn** [comment]
@olofk when you get time?

**Comment by olofk** [comment]
Terribly sorry. I completely forgot. I'll try to get to it tomorrow

**Comment by olofk** [comment]
First three commits are picked and pushed.

For some reason FuseSoC throws an exception when referencing de0_nano-multicore. Looks like it fails to parse the name. It's a FuseSoC bug and I'll look into it. Another minor thing is that `simulators = icarus` can be removed from the core file since there is no testbench. I can amend that locally and pick the last patch once I have investigated the FuseSoC error

**Comment by olofk** [comment]
Tried again and got no exception. Must had done something strange last time. All picked and pushed. Many thanks for the patches!

**Comment by stffrdhrn** [comment]
@olofk thanks

**Pull request closed without merging**
